# Generated by Django 4.2.16 on 2024-10-04 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(default='GEN', max_length=4)),
                ('number', models.IntegerField(default=1000)),
                ('title', models.CharField(default='HOOS', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoos_study_app.course'),
        ),
    ]
