# Generated by Django 5.1.1 on 2024-10-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0007_rename_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pma_admin',
            field=models.BooleanField(default=False),
        ),
    ]
