# Generated by Django 5.1.1 on 2024-10-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0008_user_is_pma_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='hoos_study_app.course'),
        ),
    ]
