# Generated by Django 4.2.16 on 2024-10-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0011_remove_studysession_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysessionavailability',
            name='available_end',
        ),
        migrations.RemoveField(
            model_name='studysessionavailability',
            name='available_start',
        ),
        migrations.AlterField(
            model_name='studysessionavailability',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Your Name'),
        ),
    ]
