# Generated by Django 4.2.16 on 2024-10-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0012_alter_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='class_documents/'),
        ),
    ]
