# Generated by Django 4.2.16 on 2024-10-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0012_remove_studysessionavailability_available_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysessionavailability',
            name='time_slots',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
