# Generated by Django 4.2.16 on 2024-11-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0013_studysessionavailability_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysessionavailability',
            name='time_slots',
            field=models.CharField(default='N/A', max_length=10000),
        ),
        migrations.AlterField(
            model_name='studysessionavailability',
            name='user_name',
            field=models.CharField(max_length=200, verbose_name='Your Name'),
        ),
    ]
