# Generated by Django 4.2.16 on 2024-10-28 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0013_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(default='No description provided.', max_length=500),
        ),
    ]
