# Generated by Django 4.2.16 on 2024-11-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0014_alter_studysessionavailability_time_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysessionavailability',
            name='time_slots',
            field=models.TextField(default='N/A'),
        ),
    ]
