# Generated by Django 4.2.16 on 2024-10-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0014_messageboard_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
