# Generated by Django 4.2.16 on 2024-10-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0015_keyword_document_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='hoos_study_app.keyword'),
        ),
    ]
