# Generated by Django 4.2.16 on 2024-10-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0015_delete_class'),
        ('hoos_study_app', '0016_alter_document_keywords'),
    ]

    operations = [
    ]
