# Generated by Django 4.2.16 on 2024-11-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0015_alter_studysessionavailability_time_slots'),
        ('hoos_study_app', '0017_merge_0015_delete_class_0016_alter_document_keywords'),
    ]

    operations = [
    ]
