# Generated by Django 4.2.16 on 2024-11-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0019_alter_studysession_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
