# Generated by Django 4.2.16 on 2024-11-11 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0020_remove_message_file_message_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
