# Generated by Django 4.2.16 on 2024-11-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0021_alter_studysession_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='created_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
