# Generated by Django 4.2.16 on 2024-11-17 08:21

from django.db import migrations, models
import hoos_study_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0024_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[hoos_study_app.models.validate_file_extension, hoos_study_app.models.validate_file_size]),
        ),
    ]
