# Generated by Django 4.2.16 on 2024-11-23 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hoos_study_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0025_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoursePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.CharField(blank=True, default=hoos_study_app.models.random_background_image, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoos_study_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
