# Generated by Django 4.2.16 on 2024-12-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0026_alter_studysessionavailability_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='description_of_location',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
