# Generated by Django 4.2.16 on 2024-12-03 23:57

from django.db import migrations, models
import hoos_study_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0027_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=hoos_study_app.models.random_profile_picture, null=True, upload_to='profile_pictures/', validators=[hoos_study_app.models.validate_file_extension, hoos_study_app.models.validate_file_size]),
        ),
    ]
