# Generated by Django 4.2.16 on 2024-12-05 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0028_alter_studysession_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hoos_study_app.course'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='room_number',
            field=models.CharField(blank=True, default='No room number provided', max_length=50, null=True),
        ),
    ]
