# Generated by Django 4.2.16 on 2024-12-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0028_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='study_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoos_study_app.studysession'),
        ),
    ]
