# Generated by Django 4.2.16 on 2024-12-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0029_document_study_session'),
        ('hoos_study_app', '0030_alter_studysession_course_name'),
    ]

    operations = [
    ]
