# Generated by Django 4.2.16 on 2024-12-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0032_studysession_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysessionavailability',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
