# Generated by Django 4.2.16 on 2024-12-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0033_studysessionavailability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysessionavailability',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
