# Generated by Django 4.2.16 on 2024-12-05 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0034_alter_studysessionavailability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysessionavailability',
            name='status',
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='hoos_study_app.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
