# Generated by Django 4.2.16 on 2024-12-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoos_study_app', '0035_remove_studysessionavailability_status_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
